version: 2
jobs:
  build:
    working_directory: ~/WordPress-Android
    docker:
      - image: circleci/android:api-24-alpha  
    environment:
      ANDROID_SDKS: android-14
      ANDROID_TARGET: android-14
      GRADLE_USER_HOME: .gradle
      GRADLE_OPTS: "-XX:MaxPermSize=4g -Xmx4g"
      MALLOC_ARENA_MAX: 2   
    
    steps:
      - checkout
      
      # Copy gradle.properties-example to gradle.properties.
      - run: cp gradle.properties-example gradle.properties
          
      - restore_cache:
          key: gradle-v1-{{ checksum "WordPress/build.gradle" }}
          
      - run: echo y | android update sdk --use-sdk-wrapper --filter android-26,build-tools-25.0.3,extra-android-m2repository,platform-tools,tools
      
      - save_cache:
          key: gradle-v1-{{ checksum "WordPress/build.gradle" }}
          paths:
            - .gradle/caches
            - .gradle/wrapper
            
      - run: ./gradlew -PdisablePreDex -Pcom.android.build.threadPoolSize=1 -Dorg.gradle.jvmargs="-Xms512m -Xmx2048m" -Dorg.gradle.daemon=false assembleVanillaRelease